container:
  image: azure-service-bus-test-client
  resourceTier: M
  port: 3011

ingress:
  host: asbtc.lynxmagnus.com

deployment: {}

configMap:
  environment: production

secret:
  secretsPath: /azure-service-bus-test-client
