services:
  azure-service-bus-test-client:
    build: 
      context: .
      target: development
    ports:
      - "3011:3011"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
