# Example docker-compose file with default Azure Service Bus connection parameters
# Copy this file to docker-compose.override.yaml or merge with your existing override file

services:
  azure-service-bus-test-client:
    build: 
      context: .
      target: development
      args:
        # Add your connection parameters here
        - DEFAULT_CONNECTION_STRING=Endpoint=sb://your-namespace.servicebus.windows.net/;SharedAccessKeyName=YourKeyName;SharedAccessKey=YourKeyValue
        - DEFAULT_QUEUE_OR_TOPIC_NAME=your-queue-or-topic-name
        - DEFAULT_SUBSCRIPTION_NAME=your-subscription-name
    environment:
      # These must match the build args above
      - DEFAULT_CONNECTION_STRING=Endpoint=sb://your-namespace.servicebus.windows.net/;SharedAccessKeyName=YourKeyName;SharedAccessKey=YourKeyValue
      - DEFAULT_QUEUE_OR_TOPIC_NAME=your-queue-or-topic-name
      - DEFAULT_SUBSCRIPTION_NAME=your-subscription-name
    ports:
      - "3011:3011"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
