version: '3.7'

# This override file should be used in development environments to
# bind-mount the app from the host into the container

services:
  azure-service-bus-test-client:
    command: npm run start:watch
    ports:
      - "3011:3011"
    volumes:
      - ./app:/node/app
      - ./package.json:/node/package.json

