version: '3.8'

# This override file should be used in development environments to
# bind-mount the app from the host into the container

services:
  azure-service-bus-test-client:
    build: 
      context: .
      target: development
    ports:
      - "3011:3011"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/node/package.json

