{{- include "helm-library.configmap" (list . "azure-service-bus-test-client.configmap") -}}
{{- define "azure-service-bus-test-client.configmap" -}}
data:
  PORT: {{ .Values.container.port | quote }}
  NODE_ENV: {{ .Values.configMap.environment | quote }}
{{- end -}}
