{{- include "helm-library.deployment" (list . "azure-service-bus-test-client.deployment") -}}
{{- define "azure-service-bus-test-client.deployment" -}}
spec:
  template:
    spec:
      containers:
      - {{ include "helm-library.container" (list . "azure-service-bus-test-client.container") }}
{{- end -}}
