{{- include "helm-library.secret" (list . "azure-service-bus-test-client.secret") -}}
{{- define "azure-service-bus-test-client.secret" -}}
data:
  COOKIE_SECRET: {{ .Values.container.cookieSecret }}
{{- end -}}
